# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-03 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(default='/avatar/default.png', null=True, upload_to='avatar_dir/'),
        ),
    ]
