# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-11 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meblog', '0002_auto_20180203_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='create_times',
        ),
    ]
